[db_credentials]
SQLITECLOUD_DBLINK="sqlitecloud://cdva0v9khz.sqlite.cloud:8860/app.sqlitecloud?"
SQLITECLOUD_APIKEY="apikey=8hOffuIB4o6s01nr7Gt4U6x6rkb0yoWHKluaRz62CQ0"
SQLITECLOUD_DBNAME="app.sqlitecloud"

[passwords]
"riccardo.baravelli@iph.it"="123"